title: i'm CJ                     # title of the site
description: quietly brilliant          # description of the site
url: https://gao.cenjie.com       # domain
baseurl:                     # root directory

# Email address
email: 

# Path of site resources
img: /assets/img 
css: /assets/css  
js:  /assets/js  
cdn: 

## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate

# paginate setting
paginate: 7

# Comment system
## Docs: https://github.com/gitalk/gitalk/blob/master/readme.md
gitalk:
  enable: false 
  clientID: 
  clientSecret: 
  repo: 
  owner: 
  admin: 
  id:      # The default is location.pathname
  title:    # Issue title
  body: 
  

# Google Analytics
## Docs: https://analytics.google.com/analytics/web/
google-analytics: 

# default layout of the articles in _post
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"